#!/bin/bash

CO='\033[0;32m'
NC='\033[0m'


printf "${CO}── Обновление и установка пакетов ──────────────────────────────────────────────${NC}\n"
sudo apt update && apt upgrade -y
sudo apt install -y	\
	cmake		\
	curl		\
	git		\
	htop		\
	vim
cp -R .config/git/ $HOME/.config/


printf "${CO}── Zsh и Oh My Zsh ─────────────────────────────────────────────────────────────${NC}\n"
sudo apt install -y zsh fonts-powerline
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
cp .zshrc $HOME


printf "${CO}── Персонализация ──────────────────────────────────────────────────────────────${NC}\n"
sudo apt install -y		\
	font-manager		\
	gtk2-engines-murrine	\
	gnome-shell-extensions	\
	gnome-themes-extra	\
	gnome-tweaks		\
	grub-customizer		\
	sassc
git clone --depth=1 https://github.com/vinceliuice/Orchis-theme.git /tmp/Orchis-theme/
bash /tmp/Orchis-theme/install.sh -t all -c dark --tweaks compact
gsettings set org.gnome.desktop.interface gtk-theme "Orchis-grey-dark-compact"
gsettings set org.gnome.shell.extensions.user-theme name "Orchis-grey-dark-compact"
git clone --depth=1 https://github.com/ryanoasis/nerd-fonts.git /tmp/nerd-fonts/
bash /tmp/nerd-fonts/install.sh JetBrainsMono
gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMonoNL Nerd Font Mono 13"


printf "${CO}── KeePassXC ───────────────────────────────────────────────────────────────────${NC}\n"
sudo apt install -y keepassxc
cp -R .config/keepassxc $HOME/.config/


printf "${CO}── Браузер, соцсети и мультимедиа ──────────────────────────────────────────────${NC}\n"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp/
sudo apt install -y /tmp/google-chrome-stable_current_amd64.deb
sudo snap install		\
	telegram-desktop	\
	discord			\
	spotify			\
	vlc
