#!/bin/bash

CO='\033[0;32m'
NC='\033[0m'

printf "${CO}── Обновление всех пакетов ─────────────────────────────────────────────────────${NC}\n"
sudo apt update
sudo apt upgrade -y

printf "${CO}── git ─────────────────────────────────────────────────────────────────────────${NC}\n"
sudo apt install -y git
cp -R .config/git/ $HOME/.config/

printf "${CO}── Другие базовые пакеты ───────────────────────────────────────────────────────${NC}\n"
sudo apt install -y	\
	cmake		\
	curl		\
	htop		\
	vim

printf "${CO}── Zsh ─────────────────────────────────────────────────────────────────────────${NC}\n"
sudo apt install -y zsh
chsh -s $(which zsh)

printf "${CO}── Oh My Zsh, плагины и тема ───────────────────────────────────────────────────${NC}\n"
sudo apt install -y fonts-powerline
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/custom/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git $ZSH/custom/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH/custom/themes/powerlevel10k
cp .zshrc $HOME

printf "${CO}── KeePassXC ───────────────────────────────────────────────────────────────────${NC}\n"
sudo snap install keepassxc
cp -R .config/keepassxc $HOME/.config/

printf "${CO}── Пакеты персонализации ───────────────────────────────────────────────────────${NC}\n"
sudo apt install -y	\
	font-manager	\
	gnome-tweaks	\
	grub-customizer

printf "${CO}── Google Chrome ───────────────────────────────────────────────────────────────${NC}\n"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp/
sudo apt install /tmp/google-chrome-stable_current_amd64.deb

printf "${CO}── Соцсети и мультимедиа ───────────────────────────────────────────────────────${NC}\n"
sudo snap install telegram-desktop discord spotify vlc
